name: Build Java with Maven & Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-jar
          path: target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Verify Target Directory
        run: ls -l target || echo "Target directory missing!"

      - name: Build Docker Image
        run: |
          if [ -d "target" ]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .
          else
            echo "Error: Target directory does not exist. Build failed."
            exit 1
          fi

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
